package pt.uminho.di.reolangeditor.editors;

import org.eclipse.swt.graphics.RGB;

public interface IReoLangColorConstants {
	RGB REOLANG_COLOR_SINGLELINE_COMMENT = new RGB(143,188,143);
	RGB REOLANG_COLOR_MULTILINE_COMMENT = new RGB(163,163,163);
	RGB REOLANG_COLOR_KEYWORDS = new RGB(139,37,01);
	RGB REOLANG_COLOR_SPECIAL_KEYWORDS = new RGB(84,84,84);
	RGB REOLANG_COLOR_OPERATORS = new RGB(0,0,205);
	RGB REOLANG_COLOR_SEPARATORS = new RGB(10,100,10);
	RGB REOLANG_COLOR_DEFAULT = new RGB(0,0,0);
	
	RGB REOLANG_CHANNELS_AND_PATTERNS = new RGB(0, 100, 230);
}
