package pt.uminho.di.cooplaeditor.reconfigurations.editors;

import org.eclipse.swt.graphics.RGB;

public interface IReCooPLaColorConstants {
	RGB RECOOPLA_COLOR_SINGLELINE_COMMENT = new RGB(143,188,143);
	RGB RECOOPLA_COLOR_MULTILINE_COMMENT = new RGB(163,163,163);
	RGB RECOOPLA_COLOR_KEYWORDS = new RGB(139,37,01);
	RGB RECOOPLA_COLOR_SPECIAL_KEYWORDS = new RGB(84,84,84);
	RGB RECOOPLA_COLOR_OPERATORS = new RGB(0,0,205);
	RGB RECOOPLA_COLOR_TYPES = new RGB(10,100,10);
	RGB RECOOPLA_COLOR_DEFAULT = new RGB(0,0,0);
	
	RGB RECOOPLA_CHANNELS_AND_PATTERNS = new RGB(0, 100, 230);
}
